version: "3"
services:
  python3:
    build: ./segregation
    container_name: "segregation"
    working_dir: "/usr/src/app"
    ports:
      - "8765:8765"
    tty: true
    volumes:
      - ./segregation:/usr/src/app
    command: python main.py